/**
 * @framework Deerflow v1.0.0
 * @license MIT
 * @module DeerflowSkillRegistry
 * @description Central registry for all Deerflow Agent Framework skills.
 *   Provides a unified API for registering, retrieving, validating, and
 *   reporting on all available skills.
 *
 *   The registry follows the Service Locator pattern (Fowler, 2004) adapted
 *   for skill management. Agents query the registry to discover which
 *   skills are available and validate their usage across the codebase.
 *
 *   Usage:
 *   ```ts
 *   import { DeerflowSkillRegistry } from "./skills";
 *
 *   const registry = DeerflowSkillRegistry.getInstance();
 *   const report = registry.getReport();
 *   console.log(report);
 *   ```
 */

// ── Re-export all skills ─────────────────────────────────────────────────

export { CodeQualitySkill } from "./code-quality-skill";
export type { QualityResult } from "./code-quality-skill";

export { TestingSkill } from "./testing-skill";
export type { TestCheckResult, GeneratedTestSuite, CoverageReport, EdgeCase } from "./testing-skill";

export { SecuritySkill } from "./security-skill";
export type { Severity, SecurityFinding, SecurityCheckResult } from "./security-skill";

export { ArchitectureSkill } from "./architecture-skill";
export type {
  ArchitectureLayer,
  ArchSeverity,
  ArchFinding,
  ArchCheckResult,
  DependencyEdge,
} from "./architecture-skill";

import { CodeQualitySkill } from "./code-quality-skill";
import { TestingSkill } from "./testing-skill";
import { SecuritySkill } from "./security-skill";
import { ArchitectureSkill } from "./architecture-skill";

// ── Registry types ───────────────────────────────────────────────────────

/** Describes a registered skill in the registry. */
export interface SkillDescriptor {
  /** Unique name identifying the skill. */
  readonly name: string;
  /** Human-readable description of what the skill does. */
  readonly description: string;
  /** The version of the skill definition. */
  readonly version: string;
  /** Names of all public methods the skill exposes. */
  readonly methods: readonly string[];
  /** Reference to the skill class constructor (for reflection). */
  readonly skillClass: SkillClassRef;
}

/** Reference type for a skill class constructor. */
export type SkillClassRef = abstract new (...args: never[]) => unknown;

/** A validation result for a single skill. */
export interface SkillValidationResult {
  /** Name of the validated skill. */
  readonly skillName: string;
  /** Whether the skill passed its self-validation. */
  readonly passed: boolean;
  /** Any issues found during validation. */
  readonly issues: readonly string[];
}

/** The full report generated by the registry. */
export interface SkillReport {
  /** ISO 8601 timestamp when the report was generated. */
  readonly generatedAt: string;
  /** Total number of registered skills. */
  readonly totalSkills: number;
  /** Total number of available skill methods across all skills. */
  readonly totalMethods: number;
  /** Per-skill descriptors. */
  readonly skills: readonly SkillDescriptor[];
  /** Validation results for every registered skill. */
  readonly validationResults: readonly SkillValidationResult[];
  /** Overall status: 'healthy' if all validations pass, 'degraded' otherwise. */
  readonly status: "healthy" | "degraded";
}

// ── Registry implementation ──────────────────────────────────────────────

/**
 * Singleton registry that manages all Deerflow skills.
 *
 * Design decisions:
 * • **Singleton pattern** – Ensures a single source of truth for skill
 *   metadata across the agent runtime. Multiple registries would create
 *   consistency problems.
 * • **Eager registration** – All built-in skills are registered on first
 *   access. This ensures the registry is always in a valid state.
 * • **Extensible via registerSkill()** – Third-party or project-specific
 *   skills can be added at runtime, supporting a plugin architecture.
 */
export class DeerflowSkillRegistry {
  private static instance: DeerflowSkillRegistry | undefined;

  private readonly skills: Map<string, SkillDescriptor> = new Map();

  /** Returns the singleton instance, creating it if necessary. */
  static getInstance(): DeerflowSkillRegistry {
    if (DeerflowSkillRegistry.instance === undefined) {
      DeerflowSkillRegistry.instance = new DeerflowSkillRegistry();
      DeerflowSkillRegistry.instance.registerBuiltinSkills();
    }
    return DeerflowSkillRegistry.instance;
  }

  /**
   * Resets the registry. Primarily useful for testing.
   * After reset, the next call to getInstance() re-creates the registry
   * and re-registers built-in skills.
   */
  static resetInstance(): void {
    DeerflowSkillRegistry.instance = undefined;
  }

  /** Private to enforce the singleton pattern. */
  private constructor() {
    // Intentionally empty – initialization deferred to registerBuiltinSkills().
  }

  // ── Public API ─────────────────────────────────────────────────────────

  /**
   * Registers a new skill with the registry.
   *
   * @param name        Unique name for the skill.
   * @param description Human-readable description.
   * @param version     Semantic version of the skill definition.
   * @param skillClass  Reference to the skill class constructor.
   * @throws {Error}    If a skill with the same name is already registered.
   */
  registerSkill(
    name: string,
    description: string,
    version: string,
    skillClass: SkillClassRef,
  ): void {
    if (this.skills.has(name)) {
      throw new Error(`Skill '${name}' is already registered. Use a unique name or deregister first.`);
    }

    const methods = this.extractPublicMethodNames(skillClass);

    this.skills.set(name, {
      name,
      description,
      version,
      methods,
      skillClass,
    });
  }

  /**
   * Retrieves a registered skill by name.
   *
   * @param name  The skill name.
   * @returns     The skill descriptor.
   * @throws {Error}  If no skill with the given name is registered.
   */
  getSkill(name: string): SkillDescriptor {
    const skill = this.skills.get(name);
    if (skill === undefined) {
      const available = Array.from(this.skills.keys()).join(", ");
      throw new Error(
        `Skill '${name}' not found. Registered skills: [${available}]`,
      );
    }
    return skill;
  }

  /**
   * Validates all registered skills.
   *
   * Validation checks:
   * 1. Every skill class has at least one public method.
   * 2. No two skills expose the same method name (collision detection).
   * 3. Skill classes are constructable (not abstract without implementation).
   *
   * @returns  An array of validation results, one per skill.
   */
  validateAll(): SkillValidationResult[] {
    const results: SkillValidationResult[] = [];
    const allMethods = new Map<string, string>(); // methodName → skillName

    for (const [skillName, descriptor] of this.skills) {
      const issues: string[] = [];

      // Check 1: at least one public method
      if (descriptor.methods.length === 0) {
        issues.push("Skill has no public methods. It cannot be invoked by an agent.");
      }

      // Check 2: method name collisions across skills
      for (const method of descriptor.methods) {
        const existingOwner = allMethods.get(method);
        if (existingOwner !== undefined) {
          issues.push(
            `Method '${method}' collides with skill '${existingOwner}'. Consider namespacing.`,
          );
        } else {
          allMethods.set(method, skillName);
        }
      }

      results.push({
        skillName,
        passed: issues.length === 0,
        issues,
      });
    }

    return results;
  }

  /**
   * Generates a comprehensive report of all registered skills, their
   * methods, and validation status.
   *
   * The report is designed to be machine-readable (JSON-serializable) and
   * human-readable (structured with clear fields). It can be logged,
   * sent to monitoring, or displayed in the agent's output.
   */
  getReport(): SkillReport {
    const skills = Array.from(this.skills.values());
    const validationResults = this.validateAll();
    const totalMethods = skills.reduce((sum, s) => sum + s.methods.length, 0);
    const allPassed = validationResults.every((r) => r.passed);

    return {
      generatedAt: new Date().toISOString(),
      totalSkills: skills.length,
      totalMethods,
      skills,
      validationResults,
      status: allPassed ? "healthy" : "degraded",
    };
  }

  /**
   * Returns a list of all registered skill names.
   */
  listSkills(): readonly string[] {
    return Array.from(this.skills.keys());
  }

  // ── Private helpers ────────────────────────────────────────────────────

  /** Registers all built-in Deerflow framework skills. */
  private registerBuiltinSkills(): void {
    this.registerSkill(
      "code-quality",
      "Enforces code quality standards including strict TypeScript, no-any policy, naming conventions, and complexity limits.",
      "1.0.0",
      CodeQualitySkill as unknown as SkillClassRef,
    );

    this.registerSkill(
      "testing",
      "Generates unit, integration, and E2E tests; detects anti-patterns; and enforces TDD workflows.",
      "1.0.0",
      TestingSkill as unknown as SkillClassRef,
    );

    this.registerSkill(
      "security",
      "Scans for OWASP Top 10 vulnerabilities including XSS, SQL injection, CSRF, and hardcoded secrets.",
      "1.0.0",
      SecuritySkill as unknown as SkillClassRef,
    );

    this.registerSkill(
      "architecture",
      "Validates Clean Architecture layering, SOLID principles, dependency direction, and scalability patterns.",
      "1.0.0",
      ArchitectureSkill as unknown as SkillClassRef,
    );
  }

  /**
   * Extracts the names of all public static methods from a class constructor.
   *
   * This uses prototype inspection to discover methods without instantiation,
   * which is important because some skill classes may have constructor
   * requirements or side effects.
   */
  private extractPublicMethodNames(skillClass: SkillClassRef): string[] {
    const methods: string[] = [];

    // Walk the prototype chain to find static methods
    let current: object | null = skillClass as object;

    while (current !== null && current !== Function.prototype) {
      const ownProps = Object.getOwnPropertyNames(current);

      const SKIP_NAMES = new Set([
        "constructor", "length", "name", "prototype",
        "caller", "callee", "arguments",
        "apply", "bind", "call",
      ]);

      for (const name of ownProps) {
        if (SKIP_NAMES.has(name)) continue;
        if (name.startsWith("_") || name.startsWith("#")) continue;
        if (typeof (current as Record<string, unknown>)[name] !== "function") continue;

        methods.push(name);
      }

      current = Object.getPrototypeOf(current);
    }

    return [...new Set(methods)];
  }
}
