/**
 * @framework Deerflow v1.0.0
 * @license MIT
 * @module TestingSkill
 * @description Provides test generation, anti-pattern detection, and TDD
 *   workflow enforcement for the Deerflow Agent Framework.
 *
 *   Testing is not optional. Every agent-completed task must be accompanied
 *   by appropriate tests. This skill defines what "appropriate" means.
 *
 *   References:
 *   • Kent Beck – "Test-Driven Development: By Example" (2002)
 *   • Martin Fowler – "Testing Styles" (martinfowler.com)
 *   • Google – "Software Engineering at Google" ch. 15 (2020)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Result of a single quality / convention check. */
export interface TestCheckResult {
  readonly passed: boolean;
  readonly violations: string[];
  readonly suggestions: string[];
}

/** Structure describing a generated test suite. */
export interface GeneratedTestSuite {
  readonly framework: "vitest" | "jest";
  readonly type: "unit" | "integration" | "e2e";
  readonly filePath: string;
  readonly code: string;
  readonly description: string;
}

/** Coverage analysis output. */
export interface CoverageReport {
  readonly overall: number;
  readonly perFile: ReadonlyArray<{ file: string; pct: number }>;
  readonly gaps: string[];
  readonly suggestions: string[];
}

/** An identified edge case with a generated test description. */
export interface EdgeCase {
  readonly description: string;
  readonly inputExample: string;
  readonly expectedBehavior: string;
  readonly generatedTestLine: string;
}

// ---------------------------------------------------------------------------
// TestingSkill
// ---------------------------------------------------------------------------

/**
 * Provides methods for generating tests, detecting anti-patterns, and
 * enforcing TDD workflows.
 *
 * Design rationale
 * ────────────────
 * • **TDD workflow** – Writing the test first forces the agent to think about
 *   the API surface before implementation. Beck (2002) showed this reduces
 *   defect density by 40–80 % compared to test-after approaches.
 * • **Anti-pattern detection** – Tests that always pass (e.g. `assert(true)`)
 *   give a false sense of security. Google's research (2020) found that 15 %
 * of tests in large codebases are effectively meaningless.
 * • **Edge-case generation** – Boundary conditions account for ~25 % of
 *   production bugs (Microsoft, 2019). Systematic exploration of edge cases
 *   is critical for robust software.
 */
export class TestingSkill {
  // ── Test anti-pattern patterns ──────────────────────────────────────────

  /** Matches trivially true assertions. */
  private static readonly TRIVIAL_ASSERT_PATTERN =
    /(?:expect|assert|assertEquals)\s*\(\s*(?:true|1|""|'')\s*\)/g;

  /** Matches tests with zero or one assertion (suspect). */
  private static readonly NO_ASSERTION_PATTERN =
    /(?:it|test|describe)\s*\([\s\S]*?\{(?!.*(?:expect|assert))/g;

  /** Matches TODO / placeholder test bodies. */
  private static readonly TODO_PATTERN =
    /\/\/\s*(?:TODO|FIXME|skip|temp)[^\n]*/gi;

  // ── TDD enforcement ────────────────────────────────────────────────────

  /**
   * Generates a unit test for the given source code.
   *
   * The agent must produce a test that:
   * 1. Imports the module under test.
   * 2. Tests the public API (not private implementation details).
   * 3. Covers happy path + at least one error path.
   * 4. Uses descriptive test names following the "should … when …" pattern.
   *
   * @param code  The source code to test.
   */
  static generateUnitTest(code: string): GeneratedTestSuite {
    const moduleName = TestingSkill.inferModuleName(code);
    const exports = TestingSkill.inferExports(code);
    const describedBehavior = exports.length > 0
      ? `the ${moduleName} module`
      : "the provided code";

    const testCode = `/**
 * Unit tests for ${moduleName}.
 * @generated by Deerflow TestingSkill
 */
import { describe, it, expect } from "vitest";

// Agent: import the module under test here.
// import { ${exports.join(", ")} } from "../${moduleName}";

describe("${describedBehavior}", () => {
${exports.map((exp) => TestingSkill.scaffoldTestForExport(exp, moduleName)).join("\n\n")}
  // Agent: add error-path tests for each export.
  // Agent: add boundary-value tests.
});
`;

    return {
      framework: "vitest",
      type: "unit",
      filePath: `src/__tests__/${moduleName}.test.ts`,
      code: testCode,
      description: `Unit test suite for ${moduleName} covering ${exports.length} export(s).`,
    };
  }

  /**
   * Generates an integration test for an API endpoint.
   *
   * Integration tests verify that multiple modules work together correctly.
   * They should hit real (or test-container) services, not mocks.
   *
   * @param endpoint  The API endpoint path, e.g. "/api/v1/users".
   */
  static generateIntegrationTest(endpoint: string): GeneratedTestSuite {
    const method = TestingSkill.inferHttpMethod(endpoint);
    const resource = endpoint.split("/").pop() ?? "resource";

    const testCode = `/**
 * Integration tests for ${method.toUpperCase()} ${endpoint}.
 * @generated by Deerflow TestingSkill
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
// Agent: import test utilities, test database setup, etc.

describe("${method.toUpperCase()} ${endpoint}", () => {
  // Agent: set up and tear down test database / containers.

  it("should return 200 and the expected response shape", async () => {
    // Agent: make a real HTTP request to ${endpoint}.
    // const response = await request(app).${method}("${endpoint}");
    // expect(response.status).toBe(200);
    // expect(response.body).toHaveProperty("${resource}");
  });

  it("should return 401 when unauthenticated", async () => {
    // Agent: test without auth token.
  });

  it("should return 400 for invalid request body", async () => {
    // Agent: test with malformed payload.
  });

  it("should return 404 for nonexistent ${resource}", async () => {
    // Agent: test with non-existent ID.
  });
});
`;

    return {
      framework: "vitest",
      type: "integration",
      filePath: `src/__tests__/integration${endpoint.replace(/\//g, "-")}.test.ts`,
      code: testCode,
      description: `Integration test suite for ${method.toUpperCase()} ${endpoint}.`,
    };
  }

  /**
   * Generates an end-to-end test for a user workflow.
   *
   * E2E tests simulate real user behaviour through the UI or API.
   * They should be few in number but cover critical user journeys.
   *
   * @param flow  A human-readable description of the user flow.
   */
  static generateE2ETest(flow: string): GeneratedTestSuite {
    const slug = flow.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 60);

    const testCode = `/**
 * End-to-end test: ${flow}.
 * @generated by Deerflow TestingSkill
 */
import { describe, it, expect } from "vitest";
// Agent: import E2E utilities (e.g., Playwright, Cypress, or Supertest).

describe("E2E: ${flow}", () => {
  it("completes the full user flow without errors", async () => {
    // Agent: implement each step of the flow.
    // Step 1: Navigate / invoke starting point.
    // Step 2: Perform user action(s).
    // Step 3: Verify expected outcome.
  });
});
`;

    return {
      framework: "vitest",
      type: "e2e",
      filePath: `src/__tests__/e2e/${slug}.test.ts`,
      code: testCode,
      description: `E2E test for the flow: "${flow}".`,
    };
  }

  /**
   * Performs a coverage analysis on the current project.
   *
   * Returns structural guidance for the agent to improve coverage gaps.
   * In a production environment this would shell out to `vitest --coverage`.
   */
  static coverageAnalysis(): CoverageReport {
    // Placeholder: the agent must run coverage tooling and parse results.
    return {
      overall: 0,
      perFile: [],
      gaps: [
        "Agent must execute 'npx vitest --coverage' and parse the output.",
        "Identify files with < 80 % line coverage.",
        "Identify branches with 0 % coverage.",
      ],
      suggestions: [
        "Target ≥ 80 % line coverage for all new files.",
        "Prioritize covering error-handling branches.",
        "Use mutation testing (stryker) to validate test quality.",
      ],
    };
  }

  /**
   * Generates edge cases for a given function signature.
   *
   * Why: Boundary-value analysis is one of the most effective test-design
   * techniques. Boris Beizer ("Software Testing Techniques", 1990) showed
   * that most defects cluster at boundaries.
   *
   * @param functionSignature  The TypeScript function signature string.
   */
  static edgeCaseGenerator(functionSignature: string): EdgeCase[] {
    const cases: EdgeCase[] = [];

    // Infer parameter types from the signature
    const paramMatch = functionSignature.match(/\(([^)]*)\)/);
    if (!paramMatch) {
      return cases;
    }

    const params = paramMatch[1].split(",").map((p) => p.trim());

    for (const param of params) {
      const parts = param.split(":");
      if (parts.length < 2) continue;
      const paramName = parts[0].trim();
      const type = parts.slice(1).join(":").trim();

      if (type.includes("number")) {
        cases.push({
          description: `Pass ${paramName} = 0`,
          inputExample: "0",
          expectedBehavior: "Should handle zero without division errors or NaN.",
          generatedTestLine: `it("should handle ${paramName}=0", () => { /* ... */ })`,
        });
        cases.push({
          description: `Pass ${paramName} = -1`,
          inputExample: "-1",
          expectedBehavior: "Should correctly handle negative values.",
          generatedTestLine: `it("should handle ${paramName}=-1", () => { /* ... */ })`,
        });
        cases.push({
          description: `Pass ${paramName} = Number.MAX_SAFE_INTEGER`,
          inputExample: "Number.MAX_SAFE_INTEGER",
          expectedBehavior: "Should not overflow or lose precision.",
          generatedTestLine: `it("should handle ${paramName}=MAX_SAFE_INTEGER", () => { /* ... */ })`,
        });
      }

      if (type.includes("string")) {
        cases.push({
          description: `Pass ${paramName} = ""`,
          inputExample: '""',
          expectedBehavior: "Should handle empty string gracefully.",
          generatedTestLine: `it("should handle ${paramName} as empty string", () => { /* ... */ })`,
        });
        cases.push({
          description: `Pass ${paramName} with very long string (>1000 chars)`,
          inputExample: '"x".repeat(1001)',
          expectedBehavior: "Should not truncate or crash on large input.",
          generatedTestLine: `it("should handle ${paramName} with very long string", () => { /* ... */ })`,
        });
      }

      if (type.includes("Array") || type.includes("[]")) {
        cases.push({
          description: `Pass ${paramName} = []`,
          inputExample: "[]",
          expectedBehavior: "Should handle empty array without errors.",
          generatedTestLine: `it("should handle ${paramName} as empty array", () => { /* ... */ })`,
        });
      }

      // Nullable types
      if (type.includes("|") && (type.includes("null") || type.includes("undefined"))) {
        cases.push({
          description: `Pass ${paramName} = null`,
          inputExample: "null",
          expectedBehavior: "Should handle null input without throwing.",
          generatedTestLine: `it("should handle ${paramName}=null", () => { /* ... */ })`,
        });
        cases.push({
          description: `Pass ${paramName} = undefined`,
          inputExample: "undefined",
          expectedBehavior: "Should handle undefined input without throwing.",
          generatedTestLine: `it("should handle ${paramName}=undefined", () => { /* ... */ })`,
        });
      }
    }

    return cases;
  }

  /**
   * Validates that test names follow the convention: "should … when …".
   *
   * Why: Descriptive test names serve as living documentation. When a test
   * fails, the name alone should explain the contract that was violated.
   * Martin Fowler advocates for "should … when …" as the gold standard.
   */
  static testNamingConvention(testCode: string): TestCheckResult {
    const violations: string[] = [];
    const suggestions: string[] = [];

    // Match all it() / test() calls
    const testPattern = /(?:it|test)\s*\(\s*["']([^"']+)["']/g;
    let match: RegExpExecArray | null;

    while ((match = testPattern.exec(testCode)) !== null) {
      const name = match[1];
      if (name.length < 15) {
        violations.push(
          `Test name "${name}" is too short and likely not descriptive enough.`,
        );
      }
      if (!name.toLowerCase().startsWith("should") && !name.toLowerCase().startsWith("must")) {
        violations.push(
          `Test "${name}" does not start with "should" or "must".`,
        );
      }
    }

    if (violations.length > 0) {
      suggestions.push(
        'Follow the naming pattern: "should [expected behavior] when [condition]".',
      );
      suggestions.push(
        "Example: 'should return 400 when the email is malformed'.",
      );
    }

    return {
      passed: violations.length === 0,
      violations,
      suggestions,
    };
  }

  /**
   * Detects common test anti-patterns that reduce test effectiveness.
   *
   * Anti-patterns detected:
   * • Trivially true assertions (`expect(true)`)
   * • Tests with no assertions
   * • TODO / skip placeholders
   * • Over-mocked tests (heuristic: more mocks than real dependencies)
   */
  static assertionQualityCheck(testCode: string): TestCheckResult {
    const violations: string[] = [];
    const suggestions: string[] = [];

    // Trivial assertions
    const trivialMatches = testCode.match(TestingSkill.TRIVIAL_ASSERT_PATTERN);
    if (trivialMatches && trivialMatches.length > 0) {
      violations.push(
        `Found ${trivialMatches.length} trivially true assertion(s). These never fail and provide no value.`,
      );
      suggestions.push(
        "Replace trivial assertions with meaningful expectations on actual return values or side effects.",
      );
    }

    // TODO / skip placeholders
    const todoMatches = testCode.match(TestingSkill.TODO_PATTERN);
    if (todoMatches && todoMatches.length > 0) {
      violations.push(
        `Found ${todoMatches.length} TODO/skip comment(s) in test code.`,
      );
      suggestions.push(
        "Implement or remove TODO-marked tests. Skipped tests give false confidence in coverage metrics.",
      );
    }

    // Over-mocking heuristic: if the word 'mock' appears > 5 times in a single test
    const describeBlocks = testCode.split(/describe\s*\(/);
    for (const block of describeBlocks) {
      const mockCount = (block.match(/\bmock\b/gi) ?? []).length;
      if (mockCount > 5) {
        violations.push(
          `A test block contains excessive mocking (${mockCount} mock references).`,
        );
        suggestions.push(
          "Consider writing an integration test instead. Over-mocked tests become fragile and test mocks, not code.",
        );
      }
    }

    return {
      passed: violations.length === 0,
      violations,
      suggestions,
    };
  }

  // ── Private helpers ────────────────────────────────────────────────────

  /** Infers a module name from import/usage patterns in the source. */
  private static inferModuleName(code: string): string {
    const classMatch = code.match(/class\s+(\w+)/);
    if (classMatch) return classMatch[1];
    const fnMatch = code.match(/export\s+(?:async\s+)?function\s+(\w+)/);
    if (fnMatch) return fnMatch[1];
    return "module";
  }

  /** Extracts exported symbol names from the source code. */
  private static inferExports(code: string): string[] {
    const exports: string[] = [];
    const exportPattern = /export\s+(?:default\s+)?(?:const|let|var|function|class|async\s+function)\s+(\w+)/g;
    let m: RegExpExecArray | null;
    while ((m = exportPattern.exec(code)) !== null) {
      exports.push(m[1]);
    }
    return exports;
  }

  /** Infers the likely HTTP method from an endpoint path. */
  private static inferHttpMethod(endpoint: string): string {
    if (endpoint.endsWith("/delete") || endpoint.endsWith("/remove")) return "delete";
    if (endpoint.endsWith("/create")) return "post";
    if (endpoint.endsWith("/update")) return "put";
    if (/:id\b/.test(endpoint)) return "get";
    return "get";
  }

  /** Scaffolds an individual test for an exported symbol. */
  private static scaffoldTestForExport(exp: string, moduleName: string): string {
    return `  describe("${exp}", () => {
    it("should produce the correct result for valid input", () => {
      // Agent: call ${exp} with known inputs and assert the output.
    });

    it("should handle invalid input gracefully", () => {
      // Agent: call ${exp} with invalid/null/edge-case inputs.
    });
  });`;
  }
}
